apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: k8sjob
spec:
  template:
    spec:
      initContainers:
        - name: init-myservice-1
          image: busybox:1.28
          command: ["sh","-c", "echo init1 >>/cache/log"]
          volumeMounts:
          - mountPath: /cache
            name: shared-data
        - name: init-myservice-2
          image: busybox:1.28
          command: ["sh","-c", "echo init2 >>/cache/log"]
          volumeMounts:
          - mountPath: /cache
            name: shared-data
      containers:
      - name: pi
        image: busybox:1.28
        command: ["sh","-c","cat /cache/log"]
        volumeMounts:
        - mountPath: /cache
          name: shared-data
      restartPolicy: Never
      volumes:
        - name: shared-data
          emptyDir: {}
  backoffLimit: 4

